"""
Primera Estrategia — H1
ADX+DI crossover strategy with pyramiding and dynamic sizing.
Generated by Strategy Builder. Edit via the Builder UI, not this file.
"""

import pandas as pd

TIMEFRAME = "H1"
MAGIC_NUMBER = 42501
ATR_14_PERIOD = 14
ADX_DI_14_PERIOD = 14
VOLUME_RATIO_20_LOOKBACK = 20

DATA_WINDOW_FIELDS = [
    {"key": "atr_14", "label": "ATR (14)", "format": "price", "section": "Volatility"},
    {"key": "atr_pct_14", "label": "ATR % (14)", "format": "percent", "section": "Volatility"},
    {"key": "adx_14", "label": "ADX (14)", "format": "number", "section": "ADX"},
    {"key": "plus_di_14", "label": "+DI (14)", "format": "number", "section": "ADX"},
    {"key": "minus_di_14", "label": "-DI (14)", "format": "number", "section": "ADX"},
    {"key": "plus_di_cross_14", "label": "+DI Cross (14)", "format": "int", "section": "ADX"},
    {"key": "minus_di_cross_14", "label": "-DI Cross (14)", "format": "int", "section": "ADX"},
    {"key": "volume_ratio_20", "label": "Volume Ratio (20)", "format": "number", "section": "Volume"},
    {"key": "up_sig", "label": "Buy Signal", "format": "int", "section": "Signals", "shift": 1},
    {"key": "dn_sig", "label": "Sell Signal", "format": "int", "section": "Signals", "shift": 1},
]

def _numeric(df: pd.DataFrame, key: str) -> pd.Series:
    return pd.to_numeric(df.get(key), errors="coerce")

def _volume_series(df: pd.DataFrame) -> pd.Series:
    if "tick_volume" in df.columns:
        return pd.to_numeric(df.get("tick_volume"), errors="coerce")
    if "volume" in df.columns:
        return pd.to_numeric(df.get("volume"), errors="coerce")
    return pd.Series(1.0, index=df.index, dtype="float64")

def _atr(high: pd.Series, low: pd.Series, close: pd.Series, length: int) -> pd.Series:
    prev_close = close.shift(1)
    tr = pd.concat(
        [high - low,
         (high - prev_close).abs(),
         (low  - prev_close).abs()],
        axis=1,
    ).max(axis=1)
    return tr.ewm(alpha=1.0 / length, min_periods=length, adjust=False).mean()

def _adx_di(high: pd.Series, low: pd.Series, close: pd.Series, length: int):
    prev_close = close.shift(1)
    tr = pd.concat(
        [high - low,
         (high - prev_close).abs(),
         (low  - prev_close).abs()],
        axis=1,
    ).max(axis=1)
    up_move   = high - high.shift(1)
    down_move = low.shift(1) - low
    import numpy as _np
    plus_dm  = pd.Series(_np.where((up_move > down_move) & (up_move > 0),   up_move,   0.0), index=high.index)
    minus_dm = pd.Series(_np.where((down_move > up_move) & (down_move > 0), down_move, 0.0), index=high.index)
    alpha = 1.0 / length
    kw = {"alpha": alpha, "min_periods": length, "adjust": False}
    atr_w     = tr.ewm(**kw).mean()
    safe_atr  = atr_w.replace(0.0, float("nan"))
    plus_di   = 100.0 * plus_dm.ewm(**kw).mean()  / safe_atr
    minus_di  = 100.0 * minus_dm.ewm(**kw).mean() / safe_atr
    di_sum    = (plus_di + minus_di).replace(0.0, float("nan"))
    dx        = 100.0 * (plus_di - minus_di).abs() / di_sum
    adx       = dx.ewm(**kw).mean()
    pprev, mprev = plus_di.shift(1), minus_di.shift(1)
    plus_cross  = ((plus_di  > minus_di) & (pprev <= mprev)).astype(int)
    minus_cross = ((minus_di > plus_di)  & (mprev <= pprev)).astype(int)
    return adx, plus_di, minus_di, plus_cross, minus_cross

def prepare_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    required = {'close', 'high', 'low'}
    if not required.issubset(out.columns):
        return out
    close = _numeric(out, "close")
    high  = _numeric(out, "high")
    low   = _numeric(out, "low")
    volume = _volume_series(out)
    atr_14     = _atr(high, low, close, 14)
    atr_pct_14 = atr_14 / close.replace(0.0, float('nan'))
    adx_14, plus_di_14, minus_di_14, plus_di_cross_14, minus_di_cross_14 = _adx_di(high, low, close, 14)
    vol_ma_20       = volume.rolling(20, min_periods=5).mean()
    volume_ratio_20 = volume / vol_ma_20.replace(0.0, float('nan'))
    out["atr_14"] = atr_14
    out["atr_pct_14"] = atr_pct_14
    out["adx_14"] = adx_14
    out["plus_di_14"] = plus_di_14
    out["minus_di_14"] = minus_di_14
    out["plus_di_cross_14"] = plus_di_cross_14
    out["minus_di_cross_14"] = minus_di_cross_14
    out["volume_ratio_20"] = volume_ratio_20
    return out

def compute_signals(df: pd.DataFrame, enable_signals: bool) -> pd.DataFrame:
    out = df.copy()
    needed = {'adx_14', 'plus_di_cross_14'}
    if not needed.issubset(out.columns):
        out["long_setup"]  = 0
        out["short_setup"] = 0
        out["up_sig"]      = 0
        out["dn_sig"]      = 0
        return out

    if enable_signals:
        buy_signal  = ((out["adx_14"] > 25) & (out["plus_di_cross_14"] > 0))
        sell_signal = (out["adx_14"] < 0)
    else:
        buy_signal  = pd.Series(False, index=out.index)
        sell_signal = pd.Series(False, index=out.index)

    out["long_setup"]  = buy_signal.astype(int)
    out["short_setup"] = sell_signal.astype(int)
    out["up_sig"]      = buy_signal.astype(int)
    out["dn_sig"]      = sell_signal.astype(int)
    return out

def get_last_signal_payload(df: pd.DataFrame, verbose: bool = False) -> dict:
    signal = get_last_signal(df, verbose=verbose)
    reasons = {
        "buy":  "Primera Estrategia: buy condition met",
        "sell": "Primera Estrategia: sell condition met",
        "none": "Primera Estrategia: no signal",
    }
    if signal == "buy":
        return {
            "signal": signal,
            "reason": reasons[signal],
            "pyramiding": True,
            "atr_value": df.iloc[-2]["atr_14"],
            "dynamic_sizing": True,
            "volume_ratio": df.iloc[-2]["volume_ratio_20"],
        }
    return {"signal": signal, "reason": reasons[signal]}

def get_last_signal(df: pd.DataFrame, verbose: bool = False) -> str:
    if df is None or len(df) < 3:
        return "none"
    if (df.iloc[-2]["adx_14"] > 25 and df.iloc[-2]["plus_di_cross_14"] > 0):
        return "buy"
    elif df.iloc[-2]["adx_14"] < 0:
        return "sell"
    return "none"
